### ISSUE TITLE
#include"atomicpp.h" No atomicpp.h file found in the source code

### ISSUE THREAD

**Issue by ssthurai** [J-Fabila/VASP_to_XYZ#1]
Dear Fabila, this file 'atomicpp.h' is missing in the source code.
Is this file available in another repository (following) of yours?
https://github.com/J-Fabila/Atomic.h/blob/master/Cpp-version/atomic.hpp

**Comment by J-Fabila** [comment]
Hello!, I already upload the necessary atomicpp.h to the master branch. Please let me know if it works. Regards.
